### PR TITLE
Focus the  text input on non-mobile devices

### LINKED ISSUE #73: Autofocus the input
It would be amazing if you autofocus the search input. 😁 Then we wouldn't have to click on that input.

Thanks for amazing product!

### PR DESCRIPTION
**Pull request by IonicaBizau**
Fixes #73. 🚀

### CODE REVIEW

**Comment by satazor** [comment]
@IonicaBizau this can't be done in the index page, but in the Search component. Also the mobile detection is pretty naive.

**Comment by IonicaBizau** [comment]
@satazor I'm not really familiar with the code—what file should be edited?

That's the easiest way to check if it's mobile or not. 😁 We can check for the touchevents in the `window`.

**Comment by satazor** [comment]
Add `componentDidMount` after this code here: https://github.com/npms-io/npms-www/blob/master/src/shared/containers/search-box/SearchBox.js

**Comment by satazor** [comment]
https://github.com/npms-io/npms-www/commit/49ab663d9ff7335c85ca10a960ff97cf5f9b0d95

**Pull request closed without merging**
